handler: lambdas/serve/serve.handler
name: serve
layers:
  - { Ref: ApiLayerLambdaLayer }
package:
  include:
    - lambdas/serve/serve.js
events:
  - http:
      method: get
      path: hello
      cors: true
