handler: lambdas/serve/serve.handler
name: serve
package:
  include:
    - lambdas/serve/serve.js
events:
  # attach the function to the root of the API...
  - http:
      path: /
      method: get
      cors: true
      kaskadi-docs:
        description: This endpoint returns the required HTML content to start the Kaskadi application.
        queryStringParameters:
          - key: host
            description: Hosting server for all apps/assets.
            default: Kaskadi public CDN
        examples:
          - request: {}
            response:
              statusCode: 200
              headers:
                'Access-Control-Allow-Origin': '*'
                'content-type': 'text/html'
              body: '<head>\n  <meta charset="utf-8">\n  <meta name="viewport" content="width=device-width, initial-scale=1">\n  <title>Kaskadi app</title>\n  <link rel="icon" type="image/png" href="https://cdn.klimapartner.net/imgs/icons/favicon.png">\n  <script type="module" src="https://cdn.klimapartner.net/modules/@kaskadi/kaskadi-apps/kaskadi-app.js"></script>\n  <style>\n    html, body {\n      margin: 0;\n      padding: 0;\n      font-family: sans-serif;\n      font-size: 16px;\n    }\n  </style>\n</head>\n<body>\n  <kaskadi-app appVersion="1.0.0"></kaskadi-app>\n</body>'
          - request:
              queryStringParameters:
                host: localhost:3000
            response:
              statusCode: 200
              headers:
                'Access-Control-Allow-Origin': '*'
                'content-type': 'text/html'
              body: '<head>\n  <meta charset="utf-8">\n  <meta name="viewport" content="width=device-width, initial-scale=1">\n  <title>Kaskadi app</title>\n  <link rel="icon" type="image/png" href="https://cdn.klimapartner.net/imgs/icons/favicon.png">\n  <script type="module" src="https://cdn.klimapartner.net/modules/@kaskadi/kaskadi-apps/kaskadi-app.js"></script>\n  <style>\n    html, body {\n      margin: 0;\n      padding: 0;\n      font-family: sans-serif;\n      font-size: 16px;\n    }\n  </style>\n</head>\n<body>\n  <kaskadi-app appVersion="1.0.0"></kaskadi-app>\n</body>'
  # and to all subsequent paths
  - http:
      path: /{proxy+}
      method: get
      cors: true
      kaskadi-docs:
        description: This endpoint returns the required HTML content to start the Kaskadi application.
        queryStringParameters:
          - key: host
            description: Hosting server for all apps/assets.
            default: Kaskadi public CDN
        examples:
          - request:
              pathParameters:
                proxy+: we_can_type_anything_here
            response:
              statusCode: 200
              headers:
                'Access-Control-Allow-Origin': '*'
                'content-type': 'text/html'
              body: '<head>\n  <meta charset="utf-8">\n  <meta name="viewport" content="width=device-width, initial-scale=1">\n  <title>Kaskadi app</title>\n  <link rel="icon" type="image/png" href="https://cdn.klimapartner.net/imgs/icons/favicon.png">\n  <script type="module" src="https://cdn.klimapartner.net/modules/@kaskadi/kaskadi-apps/kaskadi-app.js"></script>\n  <style>\n    html, body {\n      margin: 0;\n      padding: 0;\n      font-family: sans-serif;\n      font-size: 16px;\n    }\n  </style>\n</head>\n<body>\n  <kaskadi-app appVersion="1.0.0"></kaskadi-app>\n</body>'
          - request:
              pathParameters:
                proxy+: we_really_can_type_anything_here
              queryStringParameters:
                host: localhost:3000
            response:
              statusCode: 200
              headers:
                'Access-Control-Allow-Origin': '*'
                'content-type': 'text/html'
              body: '<head>\n  <meta charset="utf-8">\n  <meta name="viewport" content="width=device-width, initial-scale=1">\n  <title>Kaskadi app</title>\n  <link rel="icon" type="image/png" href="https://cdn.klimapartner.net/imgs/icons/favicon.png">\n  <script type="module" src="https://cdn.klimapartner.net/modules/@kaskadi/kaskadi-apps/kaskadi-app.js"></script>\n  <style>\n    html, body {\n      margin: 0;\n      padding: 0;\n      font-family: sans-serif;\n      font-size: 16px;\n    }\n  </style>\n</head>\n<body>\n  <kaskadi-app appVersion="1.0.0"></kaskadi-app>\n</body>'
