handler: lambdas/serve/serve.handler
name: serve
package:
  include:
    - lambdas/serve/serve.js
events:
  # attach the function to the root of the API...
  - http:
      path: /
      method: get
      cors: true
      kaskadi-docs:
        description: This endpoint returns the required HTML content to start the Kaskadi application.
        queryStringParameters:
          - key: host
            description: Hosting server for all apps/assets.
            default: Kaskadi public CDN
  # and to all subsequent paths
  - http:
      path: /{proxy+}
      method: get
      cors: true
      kaskadi-docs:
        description: This endpoint returns the required HTML content to start the Kaskadi application.
        queryStringParameters:
          - key: host
            description: Hosting server for all apps/assets.
            default: Kaskadi public CDN
